name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/
        if-no-files-found: error
