name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install texlive and plantuml
      run: sudo apt-get install texlive latexmk plantuml

    - name: Build files
      run: make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        path: |
            build/main.pdf
            build/slides/slides.pdf
